/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicWorkerSyncRouteImport } from './routes/api/public/worker-sync'
import { Route as ApiPublicTickEngineRouteImport } from './routes/api/public/tick-engine'
import { Route as AuthenticatedAdminBrainRouteImport } from './routes/_authenticated/admin/brain'

const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/_authenticated/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerSyncRoute = ApiPublicWorkerSyncRouteImport.update({
  id: '/api/public/worker-sync',
  path: '/api/public/worker-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTickEngineRoute = ApiPublicTickEngineRouteImport.update({
  id: '/api/public/tick-engine',
  path: '/api/public/tick-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBrainRoute = AuthenticatedAdminBrainRouteImport.update({
  id: '/_authenticated/admin/brain',
  path: '/admin/brain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin/brain': typeof AuthenticatedAdminBrainRoute
  '/api/public/tick-engine': typeof ApiPublicTickEngineRoute
  '/api/public/worker-sync': typeof ApiPublicWorkerSyncRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/admin/brain': typeof AuthenticatedAdminBrainRoute
  '/api/public/tick-engine': typeof ApiPublicTickEngineRoute
  '/api/public/worker-sync': typeof ApiPublicWorkerSyncRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/admin/brain': typeof AuthenticatedAdminBrainRoute
  '/api/public/tick-engine': typeof ApiPublicTickEngineRoute
  '/api/public/worker-sync': typeof ApiPublicWorkerSyncRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin/brain'
    | '/api/public/tick-engine'
    | '/api/public/worker-sync'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/brain'
    | '/api/public/tick-engine'
    | '/api/public/worker-sync'
    | '/admin'
  id:
    | '__root__'
    | '/_authenticated/admin/brain'
    | '/api/public/tick-engine'
    | '/api/public/worker-sync'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAdminBrainRoute: typeof AuthenticatedAdminBrainRoute
  ApiPublicTickEngineRoute: typeof ApiPublicTickEngineRoute
  ApiPublicWorkerSyncRoute: typeof ApiPublicWorkerSyncRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker-sync': {
      id: '/api/public/worker-sync'
      path: '/api/public/worker-sync'
      fullPath: '/api/public/worker-sync'
      preLoaderRoute: typeof ApiPublicWorkerSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tick-engine': {
      id: '/api/public/tick-engine'
      path: '/api/public/tick-engine'
      fullPath: '/api/public/tick-engine'
      preLoaderRoute: typeof ApiPublicTickEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/brain': {
      id: '/_authenticated/admin/brain'
      path: '/admin/brain'
      fullPath: '/admin/brain'
      preLoaderRoute: typeof AuthenticatedAdminBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAdminBrainRoute: AuthenticatedAdminBrainRoute,
  ApiPublicTickEngineRoute: ApiPublicTickEngineRoute,
  ApiPublicWorkerSyncRoute: ApiPublicWorkerSyncRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
