/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicWorkerSyncRouteImport } from './routes/api/public/worker-sync'
import { Route as ApiPublicTickEngineRouteImport } from './routes/api/public/tick-engine'
import { Route as AuthenticatedAdminBrainRouteImport } from './routes/_authenticated/admin/brain'
import { Route as ApiPublicDerivCallbackRouteImport } from './routes/api/public/deriv/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/_authenticated/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerSyncRoute = ApiPublicWorkerSyncRouteImport.update({
  id: '/api/public/worker-sync',
  path: '/api/public/worker-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTickEngineRoute = ApiPublicTickEngineRouteImport.update({
  id: '/api/public/tick-engine',
  path: '/api/public/tick-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBrainRoute = AuthenticatedAdminBrainRouteImport.update({
  id: '/_authenticated/admin/brain',
  path: '/admin/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDerivCallbackRoute = ApiPublicDerivCallbackRouteImport.update({
  id: '/api/public/deriv/callback',
  path: '/api/public/deriv/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/admin/brain': typeof AuthenticatedAdminBrainRoute
  '/api/public/tick-engine': typeof ApiPublicTickEngineRoute
  '/api/public/worker-sync': typeof ApiPublicWorkerSyncRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/deriv/callback': typeof ApiPublicDerivCallbackRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin/brain': typeof AuthenticatedAdminBrainRoute
  '/api/public/tick-engine': typeof ApiPublicTickEngineRoute
  '/api/public/worker-sync': typeof ApiPublicWorkerSyncRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/deriv/callback': typeof ApiPublicDerivCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/_authenticated/admin/brain': typeof AuthenticatedAdminBrainRoute
  '/api/public/tick-engine': typeof ApiPublicTickEngineRoute
  '/api/public/worker-sync': typeof ApiPublicWorkerSyncRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/deriv/callback': typeof ApiPublicDerivCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/admin/brain'
    | '/api/public/tick-engine'
    | '/api/public/worker-sync'
    | '/admin/'
    | '/api/public/deriv/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin/brain'
    | '/api/public/tick-engine'
    | '/api/public/worker-sync'
    | '/admin'
    | '/api/public/deriv/callback'
  id:
    | '__root__'
    | '/auth'
    | '/_authenticated/admin/brain'
    | '/api/public/tick-engine'
    | '/api/public/worker-sync'
    | '/_authenticated/admin/'
    | '/api/public/deriv/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  AuthenticatedAdminBrainRoute: typeof AuthenticatedAdminBrainRoute
  ApiPublicTickEngineRoute: typeof ApiPublicTickEngineRoute
  ApiPublicWorkerSyncRoute: typeof ApiPublicWorkerSyncRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  ApiPublicDerivCallbackRoute: typeof ApiPublicDerivCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker-sync': {
      id: '/api/public/worker-sync'
      path: '/api/public/worker-sync'
      fullPath: '/api/public/worker-sync'
      preLoaderRoute: typeof ApiPublicWorkerSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tick-engine': {
      id: '/api/public/tick-engine'
      path: '/api/public/tick-engine'
      fullPath: '/api/public/tick-engine'
      preLoaderRoute: typeof ApiPublicTickEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/brain': {
      id: '/_authenticated/admin/brain'
      path: '/admin/brain'
      fullPath: '/admin/brain'
      preLoaderRoute: typeof AuthenticatedAdminBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deriv/callback': {
      id: '/api/public/deriv/callback'
      path: '/api/public/deriv/callback'
      fullPath: '/api/public/deriv/callback'
      preLoaderRoute: typeof ApiPublicDerivCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  AuthenticatedAdminBrainRoute: AuthenticatedAdminBrainRoute,
  ApiPublicTickEngineRoute: ApiPublicTickEngineRoute,
  ApiPublicWorkerSyncRoute: ApiPublicWorkerSyncRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  ApiPublicDerivCallbackRoute: ApiPublicDerivCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
